spring:
  application:
    name: xc-govern-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/learnCmy/config-repo.git
          username: learnCmy
          password: cmy411488986
          basedir: F:\xczxEdu\xcEduService
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id

server:
  port: ${PORT:50000}